# Fastfile for F-Droid

default_platform(:android)

platform :android do
  desc "Deploy to F-Droid"
  lane :fdroid do
    # This lane is used by F-Droid to build and deploy the app
    # F-Droid will handle the build process using gradle
    
    # Metadata is handled by F-Droid using the metadata directory structure
    UI.message("Building for F-Droid...")
  end
  
  desc "Generate metadata for F-Droid"
  lane :metadata do
    # Metadata is properly configured for F-Droid submission
    UI.message("Metadata is configured in fastlane/metadata/android/en-US/")
  end
end 